# https://karpenter.sh/v0.8.0/provisioner/
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    #- key: node.kubernetes.io/instance-type
    #  operator: In
    #  values: ["t4g.xlarge", "t4g.large", "t4g.2xlarge"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 100
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000
  provider:
    subnetSelector:
      karpenter.sh/discovery: hpa-vpa-fargate-demo
    securityGroupSelector:
      kubernetes.io/cluster/hpa-vpa-fargate-demo: '*'
    # amiFamily: Bottlerocket
